//
// Created by vydra on 7/23/19.
//

#ifndef TESROUGEFALKREATH_CODE_HEADERS_INGAMELOGIC_H_
#define TESROUGEFALKREATH_CODE_HEADERS_INGAMELOGIC_H_

#define FRAMES_PER_SECOND_ 0.008


#endif  // TESROUGEFALKREATH_CODE_HEADERS_INGAMELOGIC_H_
